version: "3"

dotenv: [.env.local]

tasks:
    dev:
        desc: Start app + infra
        deps: [up]
        cmds:
            - task: run
    up:
        desc: Start the application infrastructure locally
        cmds:
            - docker compose -f docker-compose.dev.yml up -d --build
    run:
        cmds:
            - go run ./cmd/http_server/main.go -config=./configs/local.yml

    smee:
        desc: Start smee.io to forward webhooks
        cmds:
            - |
                smee -u https://smee.io/gbrbW0RXwD4ErqNa \
                    --target http://localhost:8606/webhook/issue