version: "3"

http:
    port: 8606
    read_timeout: 5s
    write_timeout: 5s
    gateway_timeout: 5s

app:
    github_queries_path: "./queries/github"
    polling_interval: 20s

rabbitmq:
    host: "localhost"
    port: 5672
    username: { $RABBITMQ_USER }
    password: { $RABBITMQ_PASSWORD }
    issue_exchange: "github_issue"

github:
    api_url: "https://api.github.com"
